# Generated by Django 2.2 on 2021-02-24 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inject_date', models.DateField(blank=True)),
                ('inject_time', models.DateField(auto_now_add=True)),
                ('blood_sugar_level', models.IntegerField(max_length=20)),
                ('is_insulin_injected', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=1, max_length=3)),
                ('quantity', models.IntegerField(max_length=10)),
                ('inject_area', models.TextField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
