# Generated by Django 2.2 on 2021-02-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_patientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='blood_sugar_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='quantity',
            field=models.CharField(max_length=10),
        ),
    ]
