# Generated by Django 2.2 on 2021-02-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20210224_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='inject_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='inject_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
